### PR TITLE
First pass at API description in markdown

### PR DESCRIPTION
**Pull request by mikekelly**
This is a proposed starting point for the API specification.

It's markdown based and includes endpoints and example payloads for:
- Customers
- Accounts
- Cards
- Customer Addresses
- Account Transactions
- Payments

### CODE REVIEW

**Comment by MarkStanhope** [comment]
1. Amend UK to read GB (ISO code).
2. Account Name is this the R035 or R039 as per https://github.com/OpenBankingStandard/open-data/blob/master/Report.md

**Comment by mikekelly** [comment]
@MarkStanhope good catch on (1) not sure about (2) what's the contention there?

**Comment by MarkStanhope** [comment]
not in the office at the moment, it is connected to using account
holder's name = human, account name = product name

**Comment by adamlsmith** [comment]
Recognising the complexity of achieving a unified data model across banks - I'm wondering if it would be useful to start to work on some schema rules and acceptance test specifications that would start to define the data model more clearly.  If you think that is useful I'm more than happy to start drafting something.

**Pull request closed without merging**
